# ===============================
# = SPRING DATA
# ===============================
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/oauth2-authirized-resource-server

mongo:
  min-connections: 2
  max-connections: 5
  connect-timeout-ms: 5000
  socket-timeout-ms: 5000